name: bleuskypromo reposter

on:
  schedule:
        - cron: "3,33 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          BSKY_USERNAME_BP: ${{ secrets.BSKY_USERNAME_BP }}
          BSKY_PASSWORD_BP: ${{ secrets.BSKY_PASSWORD_BP }}
          HOURS_BACK: "3"
          MAX_PER_RUN: "100"
          MAX_PER_USER: "3"
          SLEEP_SECONDS: "2"
          LIST_MEMBER_LIMIT: "1500"
          AUTHOR_POSTS_PER_MEMBER: "10"
          FEED_MAX_ITEMS: "500"
          HASHTAG_MAX_ITEMS: "100"
        run: |
          python bot.py

      - name: Commit state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add repost_state_bleuskypromo.json
          git diff --cached --quiet || git commit -m "Update repost state"
          git push